# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: ""
url: ""
date_format: "ordinal"
title: CQJ's BlOG
subtitle: "知行合一"
description: "这里是 Chen Qijin 的个人博客，用来归类整理我在学习生活中遇到的问题和解决方法，请随意浏览。"
keywords: Hello CM,CM,MZJ,mzj,Corkine,corkine,ma zhangjing,mazhangjing,mazj,Mazj
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Chen Qijin
organization: Shanghai Jiao Tong University
organization_url: http://www.sjtu.edu.cn
location: Shanghai, China
email: qjjin.chen.sh@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页
  # -
  #   href: /
  #   label: 主站
  -
    href: /
    label: 笔记
  -
    href: /categories/
    label: 归档
  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: qj4chen/qj4chen.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: qj4chen
zhihu_username: qj4chen

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: 
# !!!重要!!! 请修改下面两个用户名为你自己申请的
# !!!Important!!! Please modify usernames below to yours
duoshuo_username: 
disqus_username: 
# 在使用 disqus 的时候可点击显示多说评论框
lazy_load_duoshuo: 

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: 

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [RNN(LSTM, GRU), CNN, BERT, GCN*, GAN, 机器学习(LR, Tree, Bagging, Boosting, SVM, NB)]
skill_mobile_app_keywords: [数据清洗(numpy/pandas/matplotlib/plotly), 多因子策略, 价值选股与RSRS择时, 期限套利]
skill_windows_keywords: [管理学学士, 工学学士, 管理科学与工程硕士*]
